//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Warehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorie
    {
        public int CategorieID { get; set; }
        public string CategorieNaam { get; set; }
    }
}
