//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace New_Warehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klant
    {
        public int KlantId { get; set; }
        public string Voornaam { get; set; }
        public string Achternaam { get; set; }
        public string Straatnaam { get; set; }
        public Nullable<int> Huisnummer { get; set; }
        public Nullable<int> Postcode { get; set; }
        public string Gemeente { get; set; }
        public Nullable<int> Telefoonnummer { get; set; }
        public string Emaiadress { get; set; }
        public Nullable<System.DateTime> AangemaaktOp { get; set; }
        public string Opmerking { get; set; }
    }
}
